// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using team_status_undefined_backend.Migrations;

#nullable disable

namespace team_status_undefined_backend.Migrations
{
    [DbContext(typeof(BarberDbContext))]
    [Migration("20230218180942_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.3");

            modelBuilder.Entity("team_status_undefined_backend.Models.Barber", b =>
                {
                    b.Property<int>("BarberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("AuthSignInId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfilePic")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.HasKey("BarberId");

                    b.HasIndex("AuthSignInId");

                    b.ToTable("Barber");

                    b.HasData(
                        new
                        {
                            BarberId = 1,
                            Address = "123 A Road",
                            City = "Dayton",
                            Description = "Hi everyone! I've got openings, who needs a trim?",
                            FirstName = "Austin",
                            LastName = "Fogle",
                            LicenseNumber = "C123456",
                            PhoneNumber = "0123456789",
                            ProfilePic = "https://images.unsplash.com/photo-1517832606299-7ae9b720a186?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=772&q=80",
                            State = "Ohio"
                        });
                });

            modelBuilder.Entity("team_status_undefined_backend.Models.SignIn", b =>
                {
                    b.Property<int>("SignInId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.HasKey("SignInId");

                    b.ToTable("SignIns");
                });

            modelBuilder.Entity("team_status_undefined_backend.Models.Barber", b =>
                {
                    b.HasOne("team_status_undefined_backend.Models.SignIn", "Auth")
                        .WithMany()
                        .HasForeignKey("AuthSignInId");

                    b.Navigation("Auth");
                });
#pragma warning restore 612, 618
        }
    }
}
